-- Dynamic bus dispatch core schema.
-- Target: MySQL 8.0+, utf8mb4.
-- This schema is for persistent business data and algorithm results.

CREATE DATABASE IF NOT EXISTS `bus_dispatch_core`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE `bus_dispatch_core`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `bus_hotspot_forecast`;
DROP TABLE IF EXISTS `bus_driver_rest_request`;
DROP TABLE IF EXISTS `bus_vehicle_route_snapshot`;
DROP TABLE IF EXISTS `bus_vehicle_location_log`;
DROP TABLE IF EXISTS `bus_vehicle_runtime`;
DROP TABLE IF EXISTS `bus_dispatch_route_segment`;
DROP TABLE IF EXISTS `bus_dispatch_route_step`;
DROP TABLE IF EXISTS `bus_dispatch_task`;
DROP TABLE IF EXISTS `bus_order`;
DROP TABLE IF EXISTS `map_road_node`;
DROP TABLE IF EXISTS `map_poi`;
DROP TABLE IF EXISTS `bus_passenger`;
DROP TABLE IF EXISTS `bus_vehicle_driver_bind`;
DROP TABLE IF EXISTS `bus_vehicle`;
DROP TABLE IF EXISTS `bus_driver`;
DROP TABLE IF EXISTS `bus_operation_restriction_policy`;
DROP TABLE IF EXISTS `sys_tenant`;

CREATE TABLE `sys_tenant` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` varchar(32) NOT NULL COMMENT '租户ID',
  `tenant_name` varchar(128) NOT NULL COMMENT '租户名称',
  `status` varchar(32) NOT NULL DEFAULT 'enabled' COMMENT '状态:enabled/disabled',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_tenant_id` (`tenant_id`, `deleted`),
  KEY `idx_sys_tenant_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='租户表';

CREATE TABLE `bus_operation_restriction_policy` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `policy_code` varchar(64) NOT NULL COMMENT '禁区策略业务编码，可重复',
  `policy_name` varchar(128) NOT NULL COMMENT '禁区策略名称，同租户下唯一',
  `description` varchar(500) DEFAULT NULL COMMENT '禁区策略说明',
  `polygons_json` json NOT NULL COMMENT '规范化后的禁区 polygon 列表',
  `amap_avoidpolygons` text NOT NULL COMMENT '高德驾车规划 avoidpolygons 参数值',
  `polygon_count` int NOT NULL DEFAULT 0 COMMENT '禁区 polygon 数量',
  `vertex_count` int NOT NULL DEFAULT 0 COMMENT '顶点总数',
  `total_area_km2` decimal(12,6) NOT NULL DEFAULT 0.000000 COMMENT '总面积，单位平方公里',
  `status` varchar(32) NOT NULL DEFAULT 'enabled' COMMENT '策略状态：enabled/disabled',
  `is_active` tinyint NOT NULL DEFAULT 0 COMMENT '是否为当前全局生效策略',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除标记',
  `active_policy_name` varchar(128) GENERATED ALWAYS AS (CASE WHEN `deleted` = 0 THEN `policy_name` ELSE NULL END) STORED COMMENT '未删除策略名称唯一索引用生成列',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_operation_restriction_policy_name` (`tenant_id`, `active_policy_name`),
  KEY `idx_operation_restriction_policy_active` (`tenant_id`, `is_active`, `status`, `deleted`),
  KEY `idx_operation_restriction_policy_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='运营禁区策略表';

CREATE TABLE `bus_driver` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '司机主键',
  `driver_code` varchar(64) NOT NULL COMMENT '司机业务ID',
  `driver_no` varchar(64) DEFAULT NULL COMMENT '司机工号',
  `driver_name` varchar(64) NOT NULL COMMENT '司机姓名',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号',
  `license_no` varchar(64) DEFAULT NULL COMMENT '驾驶证号',
  `license_class` varchar(32) DEFAULT NULL COMMENT '准驾车型',
  `license_expire_date` date DEFAULT NULL COMMENT '驾驶证到期日',
  `service_city` varchar(64) DEFAULT NULL COMMENT '服务城市',
  `employment_status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '雇佣状态:active/inactive/blocked',
  `work_status` varchar(32) NOT NULL DEFAULT 'off_duty' COMMENT '工作状态:off_duty/listening/serving/resting',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_driver_code` (`tenant_id`, `driver_code`, `deleted`),
  UNIQUE KEY `uk_driver_no` (`tenant_id`, `driver_no`, `deleted`),
  KEY `idx_driver_phone` (`phone`),
  KEY `idx_driver_work_status` (`tenant_id`, `work_status`),
  KEY `idx_driver_employment_status` (`tenant_id`, `employment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='司机基础档案表';

CREATE TABLE `bus_vehicle` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '车辆主键',
  `vehicle_code` varchar(64) NOT NULL COMMENT '车辆业务ID',
  `plate_no` varchar(32) NOT NULL COMMENT '车牌号',
  `vehicle_type` varchar(32) NOT NULL DEFAULT 'bus' COMMENT '车辆类型:large_bus/mid_bus/small_bus/bus',
  `seat_count` int NOT NULL DEFAULT 0 COMMENT '座位数',
  `max_load_count` int NOT NULL DEFAULT 0 COMMENT '核载人数',
  `vehicle_color` varchar(32) DEFAULT NULL COMMENT '车辆颜色',
  `vehicle_length_m` decimal(6,2) DEFAULT NULL COMMENT '车辆长度米',
  `vehicle_model` varchar(128) DEFAULT NULL COMMENT '车辆型号',
  `manufacturer` varchar(128) DEFAULT NULL COMMENT '生产厂商',
  `registration_date` date DEFAULT NULL COMMENT '注册日期',
  `operation_status` varchar(32) NOT NULL DEFAULT 'offline' COMMENT '运营状态:offline/idle/serving/closing/resting/maintenance',
  `operation_mode` varchar(32) DEFAULT 'dynamic_bus' COMMENT '运营模式:dynamic_bus/custom_bus/regular',
  `current_driver_id` bigint DEFAULT NULL COMMENT '当前司机ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vehicle_code` (`tenant_id`, `vehicle_code`, `deleted`),
  UNIQUE KEY `uk_vehicle_plate` (`tenant_id`, `plate_no`, `deleted`),
  KEY `idx_vehicle_driver` (`current_driver_id`),
  KEY `idx_vehicle_operation_status` (`tenant_id`, `operation_status`),
  CONSTRAINT `fk_vehicle_current_driver` FOREIGN KEY (`current_driver_id`) REFERENCES `bus_driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆基础档案表';

CREATE TABLE `bus_vehicle_driver_bind` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `driver_id` bigint NOT NULL COMMENT '司机ID',
  `bind_status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '绑定状态:active/inactive',
  `bind_at` datetime(3) NOT NULL COMMENT '绑定时间',
  `unbind_at` datetime(3) DEFAULT NULL COMMENT '解绑时间',
  `operator` varchar(64) DEFAULT NULL COMMENT '操作人',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  KEY `idx_bind_vehicle` (`vehicle_id`, `bind_at`),
  KEY `idx_bind_driver` (`driver_id`, `bind_at`),
  KEY `idx_bind_status` (`tenant_id`, `bind_status`),
  CONSTRAINT `fk_bind_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_bind_driver` FOREIGN KEY (`driver_id`) REFERENCES `bus_driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='司机车辆绑定历史表';

CREATE TABLE `bus_passenger` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '乘客主键',
  `passenger_code` varchar(64) NOT NULL COMMENT '乘客业务ID',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `nickname` varchar(128) DEFAULT NULL COMMENT '昵称',
  `source_channel` varchar(64) DEFAULT NULL COMMENT '来源渠道:wechat_miniapp/alipay_miniapp/h5/app',
  `gender` varchar(16) DEFAULT 'unknown' COMMENT '性别:male/female/unknown',
  `passenger_level` varchar(32) DEFAULT 'normal' COMMENT '乘客等级',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态:active/inactive/blocked',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_passenger_code` (`tenant_id`, `passenger_code`, `deleted`),
  KEY `idx_passenger_phone` (`phone`),
  KEY `idx_passenger_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='乘客基础档案表';

CREATE TABLE `map_poi` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'POI主键',
  `poi_code` varchar(128) NOT NULL COMMENT 'POI业务编码',
  `poi_name` varchar(128) NOT NULL COMMENT 'POI名称',
  `poi_type` varchar(32) NOT NULL DEFAULT 'pickup_dropoff' COMMENT '类型:pickup_dropoff/hotspot/parking/service',
  `longitude` decimal(11,8) NOT NULL COMMENT '经度',
  `latitude` decimal(10,8) NOT NULL COMMENT '纬度',
  `zone` varchar(32) DEFAULT NULL COMMENT '运营分区',
  `node_code` varchar(128) DEFAULT NULL COMMENT '关联路网节点编码',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `status` varchar(32) NOT NULL DEFAULT 'enabled' COMMENT '状态:enabled/disabled',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_poi_code` (`tenant_id`, `poi_code`, `deleted`),
  KEY `idx_poi_zone_status` (`tenant_id`, `zone`, `status`),
  KEY `idx_poi_location` (`longitude`, `latitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='上下客POI表';

CREATE TABLE `map_road_node` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '路网节点主键',
  `node_code` varchar(128) NOT NULL COMMENT '路网节点编码',
  `node_name` varchar(128) DEFAULT NULL COMMENT '节点名称',
  `longitude` decimal(11,8) NOT NULL COMMENT '经度',
  `latitude` decimal(10,8) NOT NULL COMMENT '纬度',
  `zone` varchar(32) DEFAULT NULL COMMENT '分区',
  `is_poi` tinyint NOT NULL DEFAULT 0 COMMENT '是否POI节点:0否1是',
  `status` varchar(32) NOT NULL DEFAULT 'enabled' COMMENT '状态:enabled/disabled',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_road_node_code` (`tenant_id`, `node_code`, `deleted`),
  KEY `idx_road_node_zone` (`tenant_id`, `zone`),
  KEY `idx_road_node_location` (`longitude`, `latitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='路网节点表';

CREATE TABLE `bus_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单主键',
  `request_id` varchar(64) NOT NULL COMMENT '订单请求ID',
  `passenger_id` bigint DEFAULT NULL COMMENT '乘客ID',
  `passenger_code` varchar(64) DEFAULT NULL COMMENT '乘客业务ID冗余',
  `passenger_phone` varchar(32) DEFAULT NULL COMMENT '乘客手机号冗余',
  `passenger_count` int NOT NULL DEFAULT 1 COMMENT '乘车人数',
  `order_source` varchar(64) DEFAULT NULL COMMENT '订单来源',
  `status` varchar(32) NOT NULL DEFAULT 'created' COMMENT '订单状态:created/pooled/matched/waiting_pickup/riding/completed/cancelled/expired',
  `origin_lon` decimal(11,8) NOT NULL COMMENT '起点原始经度',
  `origin_lat` decimal(10,8) NOT NULL COMMENT '起点原始纬度',
  `destination_lon` decimal(11,8) NOT NULL COMMENT '终点原始经度',
  `destination_lat` decimal(10,8) NOT NULL COMMENT '终点原始纬度',
  `origin_poi_id` bigint DEFAULT NULL COMMENT '起点吸附POI',
  `destination_poi_id` bigint DEFAULT NULL COMMENT '终点吸附POI',
  `origin_node_code` varchar(128) DEFAULT NULL COMMENT '起点吸附路网节点',
  `destination_node_code` varchar(128) DEFAULT NULL COMMENT '终点吸附路网节点',
  `origin_name` varchar(128) DEFAULT NULL COMMENT '起点名称',
  `destination_name` varchar(128) DEFAULT NULL COMMENT '终点名称',
  `request_time` datetime(3) NOT NULL COMMENT '请求时间',
  `expected_pickup_earliest` datetime(3) DEFAULT NULL COMMENT '期望最早上车时间',
  `expected_pickup_latest` datetime(3) DEFAULT NULL COMMENT '期望最晚上车时间',
  `passenger_ready_time` datetime(3) DEFAULT NULL COMMENT '乘客就绪时间',
  `max_pickup_time` datetime(3) DEFAULT NULL COMMENT '最大可接驾时间',
  `max_arrival_time` datetime(3) DEFAULT NULL COMMENT '最大可送达时间',
  `assigned_vehicle_id` bigint DEFAULT NULL COMMENT '派单车辆ID',
  `assigned_driver_id` bigint DEFAULT NULL COMMENT '派单司机ID',
  `assigned_plate_no` varchar(32) DEFAULT NULL COMMENT '派单车牌冗余',
  `answer_time` datetime(3) DEFAULT NULL COMMENT '应答时间',
  `actual_pickup_time` datetime(3) DEFAULT NULL COMMENT '实际上车时间',
  `completion_time` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime(3) DEFAULT NULL COMMENT '取消时间',
  `cancel_type` varchar(64) DEFAULT NULL COMMENT '取消类型',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `actual_pickup_distance_m` decimal(12,2) DEFAULT NULL COMMENT '实际接驾距离米',
  `actual_pickup_duration_s` int DEFAULT NULL COMMENT '实际接驾时长秒',
  `loaded_distance_m` decimal(12,2) DEFAULT NULL COMMENT '载客距离米',
  `loaded_duration_s` int DEFAULT NULL COMMENT '载客时长秒',
  `route_version` varchar(128) DEFAULT NULL COMMENT '订单路线版本',
  `route_status` varchar(32) DEFAULT NULL COMMENT '订单路线状态:pending/ready/error/stale',
  `route_distance_m` decimal(12,2) DEFAULT NULL COMMENT '订单路线总距离米',
  `route_duration_s` int DEFAULT NULL COMMENT '订单路线预计耗时秒',
  `raw_route_points` json DEFAULT NULL COMMENT '算法A*生成的订单原始路线点',
  `grasped_route_points` json DEFAULT NULL COMMENT '高德纠偏后的订单路线点',
  `route_segments` json DEFAULT NULL COMMENT '订单路线分段详情',
  `route_updated_at` datetime(3) DEFAULT NULL COMMENT '订单路线更新时间',
  `route_error` varchar(500) DEFAULT NULL COMMENT '订单路线错误',
  `estimated_arrival_time` datetime(3) DEFAULT NULL COMMENT '预计接驾到达时间',
  `estimated_dropoff_time` datetime(3) DEFAULT NULL COMMENT '预计送达时间',
  `estimated_arrival_eta_seconds` int DEFAULT NULL COMMENT '预计接驾ETA秒',
  `estimated_dropoff_eta_seconds` int DEFAULT NULL COMMENT '预计送达ETA秒',
  `eta_status` varchar(32) DEFAULT NULL COMMENT 'ETA状态:pending/loading/ready/partial/not_available/eta_error/disabled',
  `eta_error` varchar(500) DEFAULT NULL COMMENT 'ETA错误',
  `eta_updated_at` datetime(3) DEFAULT NULL COMMENT 'ETA更新时间',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_request_id` (`tenant_id`, `request_id`, `deleted`),
  KEY `idx_order_passenger` (`passenger_id`, `request_time`),
  KEY `idx_order_passenger_phone_created` (`tenant_id`, `passenger_phone`, `created_at`),
  KEY `idx_order_status_time` (`tenant_id`, `status`, `request_time`),
  KEY `idx_order_created_at` (`tenant_id`, `created_at`),
  KEY `idx_order_plate_created` (`tenant_id`, `assigned_plate_no`, `created_at`),
  KEY `idx_order_vehicle_status` (`assigned_vehicle_id`, `status`),
  KEY `idx_order_eta_status` (`tenant_id`, `eta_status`, `eta_updated_at`),
  KEY `idx_order_route_status` (`tenant_id`, `route_status`, `route_updated_at`),
  CONSTRAINT `fk_order_passenger` FOREIGN KEY (`passenger_id`) REFERENCES `bus_passenger` (`id`),
  CONSTRAINT `fk_order_origin_poi` FOREIGN KEY (`origin_poi_id`) REFERENCES `map_poi` (`id`),
  CONSTRAINT `fk_order_destination_poi` FOREIGN KEY (`destination_poi_id`) REFERENCES `map_poi` (`id`),
  CONSTRAINT `fk_order_vehicle` FOREIGN KEY (`assigned_vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_order_driver` FOREIGN KEY (`assigned_driver_id`) REFERENCES `bus_driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单主表';

CREATE TABLE `bus_dispatch_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '调度任务主键',
  `task_no` varchar(64) NOT NULL COMMENT '调度任务编号',
  `task_type` varchar(32) NOT NULL COMMENT '任务类型:dispatch/replan/cancel/idle',
  `trigger_source` varchar(64) DEFAULT NULL COMMENT '触发来源:order/gps/rest/tick/manual',
  `request_id` varchar(64) DEFAULT NULL COMMENT '关联订单请求ID',
  `order_id` bigint DEFAULT NULL COMMENT '关联订单ID',
  `vehicle_id` bigint DEFAULT NULL COMMENT '触发车辆ID',
  `selected_vehicle_id` bigint DEFAULT NULL COMMENT '最终选中车辆ID',
  `route_version` varchar(128) DEFAULT NULL COMMENT '输出路线版本',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '任务状态:pending/running/success/failed/rejected',
  `candidate_vehicle_count` int DEFAULT NULL COMMENT '候选车辆数量',
  `input_summary` json DEFAULT NULL COMMENT '算法输入摘要',
  `output_summary` json DEFAULT NULL COMMENT '算法输出摘要',
  `elapsed_ms` int DEFAULT NULL COMMENT '耗时毫秒',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '错误信息',
  `started_at` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime(3) DEFAULT NULL COMMENT '结束时间',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dispatch_task_no` (`tenant_id`, `task_no`, `deleted`),
  KEY `idx_dispatch_task_order` (`order_id`),
  KEY `idx_dispatch_task_vehicle` (`vehicle_id`, `created_at`),
  KEY `idx_dispatch_task_status` (`tenant_id`, `status`, `created_at`),
  CONSTRAINT `fk_dispatch_task_order` FOREIGN KEY (`order_id`) REFERENCES `bus_order` (`id`),
  CONSTRAINT `fk_dispatch_task_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_dispatch_task_selected_vehicle` FOREIGN KEY (`selected_vehicle_id`) REFERENCES `bus_vehicle` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='派单和重规划任务表';

CREATE TABLE `bus_dispatch_route_step` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '路线步骤主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `route_version` varchar(128) NOT NULL COMMENT '路线版本',
  `sequence_no` int NOT NULL COMMENT '步骤顺序',
  `step_type` varchar(8) NOT NULL COMMENT '步骤类型:O/D',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `request_id` varchar(64) NOT NULL COMMENT '订单请求ID冗余',
  `target_poi_id` bigint DEFAULT NULL COMMENT '目标POI',
  `target_node_code` varchar(128) DEFAULT NULL COMMENT '目标路网节点',
  `target_lon` decimal(11,8) DEFAULT NULL COMMENT '目标经度',
  `target_lat` decimal(10,8) DEFAULT NULL COMMENT '目标纬度',
  `planned_arrival_time` datetime(3) DEFAULT NULL COMMENT '计划到达时间',
  `eta_seconds` int DEFAULT NULL COMMENT '预计到达秒数',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/reached/skipped/cancelled',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_step_seq` (`tenant_id`, `vehicle_id`, `route_version`, `sequence_no`, `deleted`),
  KEY `idx_route_step_order` (`order_id`, `step_type`),
  KEY `idx_route_step_status` (`vehicle_id`, `status`, `sequence_no`),
  CONSTRAINT `fk_route_step_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_route_step_order` FOREIGN KEY (`order_id`) REFERENCES `bus_order` (`id`),
  CONSTRAINT `fk_route_step_poi` FOREIGN KEY (`target_poi_id`) REFERENCES `map_poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆计划O/D步骤表';

CREATE TABLE `bus_dispatch_route_segment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '路线分段主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `route_version` varchar(128) NOT NULL COMMENT '路线版本',
  `segment_index` int NOT NULL COMMENT '分段序号',
  `segment_type` varchar(16) NOT NULL COMMENT '分段类型:O/D/IDLE',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID',
  `request_id` varchar(64) DEFAULT NULL COMMENT '订单请求ID冗余',
  `start_node_code` varchar(128) DEFAULT NULL COMMENT '起点路网节点',
  `end_node_code` varchar(128) DEFAULT NULL COMMENT '终点路网节点',
  `target_poi_id` bigint DEFAULT NULL COMMENT '目标POI',
  `raw_points` json DEFAULT NULL COMMENT 'A*原始路线点',
  `grasped_points` json DEFAULT NULL COMMENT '高德纠偏路线点',
  `distance_m` decimal(12,2) DEFAULT NULL COMMENT '分段距离米',
  `duration_s` int DEFAULT NULL COMMENT '分段预计耗时秒',
  `eta_seconds` int DEFAULT NULL COMMENT '从车辆当前位置累计ETA秒',
  `grasp_status` varchar(32) DEFAULT NULL COMMENT '纠偏状态:pending/ready/error/disabled/stale',
  `grasp_error` varchar(500) DEFAULT NULL COMMENT '纠偏错误',
  `segment_status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '分段状态:active/reached/skipped/stale',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_segment_idx` (`tenant_id`, `vehicle_id`, `route_version`, `segment_index`, `deleted`),
  KEY `idx_route_segment_order` (`order_id`, `segment_type`),
  KEY `idx_route_segment_status` (`vehicle_id`, `segment_status`, `segment_index`),
  KEY `idx_route_segment_grasp` (`tenant_id`, `grasp_status`, `updated_at`),
  CONSTRAINT `fk_route_segment_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_route_segment_order` FOREIGN KEY (`order_id`) REFERENCES `bus_order` (`id`),
  CONSTRAINT `fk_route_segment_poi` FOREIGN KEY (`target_poi_id`) REFERENCES `map_poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆路线分段表';

CREATE TABLE `bus_vehicle_runtime` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '运行态主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `driver_id` bigint DEFAULT NULL COMMENT '当前司机ID',
  `current_lon` decimal(11,8) DEFAULT NULL COMMENT '当前GPS经度',
  `current_lat` decimal(10,8) DEFAULT NULL COMMENT '当前GPS纬度',
  `speed_kmh` decimal(8,2) DEFAULT NULL COMMENT '速度km/h',
  `heading` decimal(8,2) DEFAULT NULL COMMENT '方向角',
  `last_node_code` varchar(128) DEFAULT NULL COMMENT '上一节点',
  `next_node_code` varchar(128) DEFAULT NULL COMMENT '下一节点',
  `edge_progress` decimal(10,6) DEFAULT NULL COMMENT '当前边进度0-1',
  `on_board_count` int NOT NULL DEFAULT 0 COMMENT '车上人数',
  `on_board_order_ids` json DEFAULT NULL COMMENT '车上订单ID列表',
  `planned_step_count` int NOT NULL DEFAULT 0 COMMENT '剩余计划步骤数',
  `segment_route` json DEFAULT NULL COMMENT '车辆当前高德纠偏分段路线，对应 planned_route_segment_grasped_point',
  `rest_status` varchar(32) NOT NULL DEFAULT 'operating' COMMENT '休息状态:operating/closing/resting',
  `can_accept_order` tinyint NOT NULL DEFAULT 1 COMMENT '是否可接单',
  `route_version` varchar(128) DEFAULT NULL COMMENT '当前路线版本',
  `route_grasp_status` varchar(32) DEFAULT NULL COMMENT '当前路线纠偏状态',
  `route_grasp_error` varchar(500) DEFAULT NULL COMMENT '当前路线纠偏错误',
  `idle_target_poi_id` bigint DEFAULT NULL COMMENT '空车热点目标POI',
  `idle_target_lon` decimal(11,8) DEFAULT NULL COMMENT '空车目标经度',
  `idle_target_lat` decimal(10,8) DEFAULT NULL COMMENT '空车目标纬度',
  `idle_target_eta_seconds` int DEFAULT NULL COMMENT '到热点ETA秒',
  `idle_target_eta_time` datetime(3) DEFAULT NULL COMMENT '预计到热点时间',
  `idle_target_eta_status` varchar(32) DEFAULT NULL COMMENT '热点ETA状态',
  `reported_at` datetime(3) DEFAULT NULL COMMENT '最近GPS上报时间',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_runtime_vehicle` (`tenant_id`, `vehicle_id`, `deleted`),
  KEY `idx_runtime_driver` (`driver_id`),
  KEY `idx_runtime_status` (`tenant_id`, `rest_status`, `can_accept_order`),
  KEY `idx_runtime_reported_at` (`reported_at`),
  CONSTRAINT `fk_runtime_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_runtime_driver` FOREIGN KEY (`driver_id`) REFERENCES `bus_driver` (`id`),
  CONSTRAINT `fk_runtime_idle_poi` FOREIGN KEY (`idle_target_poi_id`) REFERENCES `map_poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆当前运行快照表';

CREATE TABLE `bus_vehicle_location_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '位置日志主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `driver_id` bigint DEFAULT NULL COMMENT '司机ID',
  `longitude` decimal(11,8) NOT NULL COMMENT 'GPS经度',
  `latitude` decimal(10,8) NOT NULL COMMENT 'GPS纬度',
  `speed_kmh` decimal(8,2) DEFAULT NULL COMMENT '速度km/h',
  `heading` decimal(8,2) DEFAULT NULL COMMENT '方向角',
  `source` varchar(32) NOT NULL DEFAULT 'gps' COMMENT '来源:gps/simulator/device',
  `raw_payload` json DEFAULT NULL COMMENT '原始上报内容',
  `report_time` datetime(3) NOT NULL COMMENT '上报时间',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  KEY `idx_location_vehicle_time` (`vehicle_id`, `report_time`),
  KEY `idx_location_driver_time` (`driver_id`, `report_time`),
  KEY `idx_location_tenant_time` (`tenant_id`, `report_time`),
  CONSTRAINT `fk_location_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_location_driver` FOREIGN KEY (`driver_id`) REFERENCES `bus_driver` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆GPS历史轨迹表';

CREATE TABLE `bus_vehicle_route_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '路线快照主键',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `route_version` varchar(128) NOT NULL COMMENT '路线版本',
  `route_type` varchar(32) NOT NULL DEFAULT 'order' COMMENT '路线类型:order/idle/empty',
  `raw_route_points` json DEFAULT NULL COMMENT '整车A*原始路线',
  `grasped_route_points` json DEFAULT NULL COMMENT '整车高德纠偏路线',
  `raw_segments` json DEFAULT NULL COMMENT '原始分段',
  `grasped_segments` json DEFAULT NULL COMMENT '纠偏分段',
  `distance_m` decimal(12,2) DEFAULT NULL COMMENT '路线距离米',
  `planned_step_count` int NOT NULL DEFAULT 0 COMMENT '计划步骤数',
  `grasp_status` varchar(32) DEFAULT NULL COMMENT '纠偏状态',
  `grasp_error` varchar(500) DEFAULT NULL COMMENT '纠偏错误',
  `snapshot_status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '快照状态:active/stale/archived',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_route_snapshot_version` (`tenant_id`, `vehicle_id`, `route_version`, `deleted`),
  KEY `idx_route_snapshot_status` (`vehicle_id`, `snapshot_status`, `created_at`),
  KEY `idx_route_snapshot_grasp` (`tenant_id`, `grasp_status`, `updated_at`),
  CONSTRAINT `fk_snapshot_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆路线快照表';

CREATE TABLE `bus_driver_rest_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '休息申请主键',
  `rest_request_no` varchar(64) NOT NULL COMMENT '休息申请编号',
  `driver_id` bigint NOT NULL COMMENT '司机ID',
  `vehicle_id` bigint NOT NULL COMMENT '车辆ID',
  `desired_rest_time` datetime(3) DEFAULT NULL COMMENT '期望休息时间',
  `rest_duration_minutes` int NOT NULL DEFAULT 20 COMMENT '休息时长分钟',
  `status` varchar(32) NOT NULL DEFAULT 'requested' COMMENT '状态:requested/closing/resting/completed/cancelled/expired',
  `request_lon` decimal(11,8) DEFAULT NULL COMMENT '申请经度',
  `request_lat` decimal(10,8) DEFAULT NULL COMMENT '申请纬度',
  `requested_at` datetime(3) NOT NULL COMMENT '申请时间',
  `started_at` datetime(3) DEFAULT NULL COMMENT '开始休息时间',
  `ended_at` datetime(3) DEFAULT NULL COMMENT '结束休息时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rest_request_no` (`tenant_id`, `rest_request_no`, `deleted`),
  KEY `idx_rest_driver_time` (`driver_id`, `requested_at`),
  KEY `idx_rest_vehicle_status` (`vehicle_id`, `status`),
  CONSTRAINT `fk_rest_driver` FOREIGN KEY (`driver_id`) REFERENCES `bus_driver` (`id`),
  CONSTRAINT `fk_rest_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='司机休息申请表';

CREATE TABLE `bus_hotspot_forecast` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '热点预测主键',
  `forecast_no` varchar(64) NOT NULL COMMENT '预测编号',
  `vehicle_id` bigint DEFAULT NULL COMMENT '推荐车辆ID',
  `hotspot_poi_id` bigint DEFAULT NULL COMMENT '热点POI',
  `target_lon` decimal(11,8) NOT NULL COMMENT '热点经度',
  `target_lat` decimal(10,8) NOT NULL COMMENT '热点纬度',
  `zone` varchar(32) DEFAULT NULL COMMENT '热点分区',
  `forecast_time` datetime(3) NOT NULL COMMENT '预测生成时间',
  `window_start` datetime(3) DEFAULT NULL COMMENT '预测窗口开始',
  `window_end` datetime(3) DEFAULT NULL COMMENT '预测窗口结束',
  `score` decimal(12,4) DEFAULT NULL COMMENT '热点得分',
  `expected_demand_count` int DEFAULT NULL COMMENT '预计需求数',
  `reason_json` json DEFAULT NULL COMMENT '预测解释',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态:active/used/expired',
  `tenant_id` varchar(32) NOT NULL DEFAULT '000000' COMMENT '租户ID',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '软删除:0否1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hotspot_forecast_no` (`tenant_id`, `forecast_no`, `deleted`),
  KEY `idx_hotspot_vehicle` (`vehicle_id`, `forecast_time`),
  KEY `idx_hotspot_zone_time` (`tenant_id`, `zone`, `forecast_time`),
  KEY `idx_hotspot_status` (`tenant_id`, `status`, `forecast_time`),
  CONSTRAINT `fk_hotspot_vehicle` FOREIGN KEY (`vehicle_id`) REFERENCES `bus_vehicle` (`id`),
  CONSTRAINT `fk_hotspot_poi` FOREIGN KEY (`hotspot_poi_id`) REFERENCES `map_poi` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='空车热点预测表';

SET FOREIGN_KEY_CHECKS = 1;
